port : "8080"

db : 
      username : "crm_user_actual"
      host : "postgres"
      port : "5432"
      dbname : "crm_db"
      sslmode : "disable"
redis:
      host: "redis"
      port: "6379"
      db: 0